name: Production Pipeline

on:
  pull_request:
    branches:
    - master
    paths:
    - 'aws-infrastructure/**'
    types: [closed]

jobs:
  production-pipeline:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Cache Node dependencies
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: yarn install --no-progress --non-interactive --silent

    - name: Build
      run: yarn workspace aws-infrastructure build

    - name: Test
      run: yarn workspace aws-infrastructure test
      env:
        ENVIRONMENT_NAME: "production"
        GITHUB_PR_NUMBER: ${{ github.event.number }}

    - name: Deploy
      run: yarn workspace aws-infrastructure deploy --no-staging --require-approval never
      env:
        ENVIRONMENT_NAME: "production"
        GITHUB_PR_NUMBER: ${{ github.event.number }}
